import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ImpersonationBanner } from "@/components/impersonation-banner";
import { DropdownPortalSelect } from "@/components/dropdown-portal-select";
import { HotkeyNav } from "@/components/hotkey-nav";
import { AcknowledgeGate } from "@/components/acknowledge-gate";
import { ConvexClientProvider } from "./ConvexClientProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <ConvexClientProvider>
            <header className="flex items-center justify-between px-6 py-3 border-b border-zinc-200 dark:border-zinc-800">
              <span className="font-semibold text-sm"><a href="/">A.R.L.O.</a></span>
              <div className="flex items-center gap-3">
                <Show when="signed-out">
                  <SignInButton />
                  <SignUpButton />
                </Show>
                <Show when="signed-in">
                  <AcknowledgeGate />
                  <HotkeyNav />
                  <DropdownPortalSelect />
                  <a href="/user">My Profile</a>
                  <UserButton />
                </Show>
              </div>
            </header>
            <ImpersonationBanner />
            {children}
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
